### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MyTheValentinus** [nvkzNemo/UberSplash#1]
Hello i'm french and i would like tutorial to install UberSplash

**Comment by nvkzNemo** [comment]
Hello.

Applications will normally not load an extension unless it is cryptographically signed. However, during development we want to be able to quickly test an extension without having to sign it. To turn on debug mode:

On Mac, open the file **~/Library/Preferences/com.adobe.CSXS.4.plist** and add a row with key PlayerDebugMode, of type String, and value 1.
On Windows, open the registry key **HKEY_CURRENT_USER/Software/Adobe/CSXS.4** and add a key named PlayerDebugMode, of type String, and value 1.

You should only need to do this once.

Copying the extension into place

Now that the system is ready to load our unsigned extension, the last thing we have to do is copy our extension into the shared extensions folder on disk:

On Mac, copy the extension into **~/Library/Application Support/Adobe/CEPServiceManager4/extensions**
On Windows, copy the extension into **%APPDATA%\Adobe\CEPServiceManager4\extensions**

**Comment by MyTheValentinus** [comment]
Dont have good folder: http://www.eponacraft.eu/screen/2015-01-01_11.03.40.png

**Comment by nvkzNemo** [comment]
If the folder does not exist, then it should be created. 
.../Adobe/CEP/extensions/

**Comment by MyTheValentinus** [comment]
OK thank and drop folder UberSplah-master in the extensions folder ?

**Comment by nvkzNemo** [comment]
Yeah, right

**Comment by MyTheValentinus** [comment]
Thank you for your help but I still have a concern, the extension does not load, I think it's because I did not edit the registry, I do not have the value you provided me. http://www.eponacraft.eu/screen/2015-01-01_11.21.51.png

**Comment by nvkzNemo** [comment]
You need to create folder and key too.

**Comment by MyTheValentinus** [comment]
Okay, good loading. But gray background http://www.eponacraft.eu/screen/2015-01-01_12.11.08.png

**Comment by nvkzNemo** [comment]
hmm... May be need to reload Photoshop. 
I checked on 4 computers and everywhere worked correctly.

**Comment by MyTheValentinus** [comment]
I restart photoshop fiveteen

**Comment by nvkzNemo** [comment]
¯\_(ツ)_/¯

https://www.dropbox.com/s/orj6zr6tr97tvx9/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-01%2020.49.55.png?dl=0

https://www.dropbox.com/s/7gbwmhir65pubuo/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-01%2020.50.43.png?dl=0

**Comment by MyTheValentinus** [comment]
Yes is good thank :) UberFrame is free ?

**Comment by nvkzNemo** [comment]
$8 http://uberplugins.cc/uberframe/

**Comment by MyTheValentinus** [comment]
Ok too bad thank for all :)
